### ISSUE TITLE
Deprecate the convenience API ?

### ISSUE THREAD

**Issue by dmerejkowsky** [pyenchant/pyenchant#212]
This is a follow-up on #206. In short, even if the C Enchant library _is_ threadsafe, the "convenience API" like `dict = enchant.Dict('en')` is not.

To avoid problems with threads, it's best to always create a broker explicitly, like `broker = enchant.Broker(); dict = broker.request_dict('en')`.

So I'm tempted to just remove the API - it's just too easy to misuse ...

Of course, removing the convenience API will break a ton of existing code, so we could start by adding a deprecation message and see if people complain.

@rfk, I'd really like your opinion on this given you've worked on PyEnchant a lot more than me.

Other feedback is welcome of course.

**Comment by rfk** [comment]
> @rfk, I'd really like your opinion on this given you've worked on PyEnchant a lot more than me.

I think it's reasonable to deprecate and remove if it can't be made safe, but I'd expect it to be a pretty disruptive change since the pyenchant API tried pretty hard to make brokers a hidden implementation detail. Some half-formed thoughts below...

Would it help if we used a [`threading.local`](https://docs.python.org/3/library/threading.html#thread-local-data) to give each thread its own default broker while keeping the convenience API?

I guess I don't really understand the source of the unsafety - is it that we need to prevent concurrent access from different threads, or always use a broken from the thread it was created on, or something else?

The underlying enchant library reference-counts dictionary objects (see e.g. [here](https://github.com/AbiWord/enchant/blob/583e9e8a408536be6db0a9d217ba5c5217bc78f9/src/lib.c#L1079)) which might explain why the default broker is causing problems - you end up with multiple python `Dict` objects pointing to the same underlying `dict` struct in C, being operated on from multiple threads.

But if that *is* causing problems, there may be thread-safety issues even if we get rid of the convenience API, e.g. if you create a single `Dict` instance and then share it between two different threads will it exhibit the same crash?

So if we do remove it, are we confident that the remaining API surface is thread-safe?

**Comment by dmerejkowsky** [comment]
> So if we do remove it, are we confident that the remaining API surface is thread-safe?

Good point. Let's not do this.
