### ISSUE TITLE
Trailing numbers not consider part of a word

### ISSUE THREAD

**Issue by ktbarrett** [pyenchant/pyenchant#254]
**Environment**
Python version: 3.9
Operation system: Debian

**Additional context**
Tokenizer does not consider trailing numbers to be a part of a word. From downstream project https://github.com/sphinx-contrib/spelling/issues/126.

**Steps to Reproduce**
```python
import enchant.tokenize
tokenizer = enchant.tokenize.get_tokenizer()
for word, pos in tokenizer("pybind11"):
    print(word, pos)
```

You get
```
pybind 0
```

**Expected behavior**
I expect the trailing number to be a part of the word. The `pybind11` is an identifier. Since many programming languages and tools allow you to use numbers in an identifier in all but the first character, valid identifiers with trailing numbers (or even in the middle) are pretty common in technical writing. The tokenizer should be changed to support the following pattern for identifiers: `[_a-zA-Z][_a-zA-Z0-9]*]`.

**Comment by dmerejkowsky** [comment]
Hum. I'm wary about implementing such a change because I'm not sure how it would break things for other PyEnchant users.

Maybe the way to for you to is to write a different tokenizer and use it instead?

By the way, I wrote such a tokenizer for code *and* text but it's in Rust and it was ... non-trivial. (Full disclosure: I'm now using this project for my spell checking purposes instead of PyEnchant ...)

**Comment by dmerejkowsky** [comment]
Let's close this - it seems downstream is OK with this :)
