### ISSUE TITLE
Cannot find Enchant C library on Apple Silicon

### ISSUE THREAD

**Issue by ybm11** [pyenchant/pyenchant#265]
**Environment**
Python version: Tried both 3.7.11 at Anaconda and 3.8.9 at regular Python
Operation system: macOS Monterey 12.0.1

**Additional context**

**Steps to Reproduce**
```
brew update
brew install enchant
pip3 install pyenchant
PYENCHANT_VERBOSE_FIND=x export PYENCHANT_VERBOSE_FIND
```

**Expected behavior**
`import enchant` runs without errors

**Additional context**

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/benmalka/.conda/envs/ChargeTypesClassification/lib/python3.7/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/benmalka/.conda/envs/ChargeTypesClassification/lib/python3.7/site-packages/enchant/_enchant.py", line 157, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details
```

**Comment by ybm11** [comment]
Hi @dmerejkowsky , I checked and indeed I defined the environment variable locally instead of globally. I will update it and let you know the outcome. 
Also, I did not mention it earlier but I use Apple Silicon, could this be the cause?

**Comment by dmerejkowsky** [comment]
> I use Apple Silicon, could this be the cause?

I'm afraid so. There's already an other issue there which I think has the same root cause : #264 

But since I don't have access to Apple Silicon hardware, there's not much I could do.

**Comment by ybm11** [comment]
Thanks, then I will close this issue for now

**Comment by dmerejkowsky** [comment]
No need to close, if this indeed a bug relate to Apple Silicon (we still need to make sure of that) we need people to know about it - and hopefully we'll get help from someone else :)

**Comment by undo76** [comment]
I am having the same problem with the homebrew aarch64 version of enchant under Apple Silicon macOS Monterey 12.0.1. 

I have installed an x86_64 version of homebrew in /usr/local in order to download the x86_64 version of enchant and it seems to work now. I know that this solution is not ideal and it is just a workaround. I don't know if this was working before as it is the first time I have used this lib.

```bash
$ arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
$ arch -x86_64 /usr/local/bin/brew install enchant
```

**Comment by dmerejkowsky** [comment]
OK, I think we can agree the problem is specific to Apple Silicon. The workaround may have its place in the documentation. @undo76 : wanna try and submit a patch ?

**Comment by ybm11** [comment]
When I run the commands @undo76 mentioned above, I get the following incompatibility error (As expected, I guess):

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/benmalka/miniforge3/envs/ChargeTypesClassification/lib/python3.8/site-packages/enchant/__init__.py", line 81, in <module>
    from enchant import _enchant as _e
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/benmalka/miniforge3/envs/ChargeTypesClassification/lib/python3.8/site-packages/enchant/_enchant.py", line 161, in <module>
    e = ctypes.cdll.LoadLibrary(enchant_lib_path)
  File "/Users/benmalka/miniforge3/envs/ChargeTypesClassification/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/Users/benmalka/miniforge3/envs/ChargeTypesClassification/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/libenchant-2.dylib, 0x0006): tried: '/usr/local/lib/libenchant-2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libenchant-2.dylib' (no such file), '/usr/local/Cellar/enchant/2.3.1/lib/libenchant-2.2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libenchant-2.2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/libenchant-2.2.dylib' (no such file)

```

**Comment by Simonmaignan** [comment]
I also followed the step from @undo76 to install the x86_64 version of enchant and am now stuck with the same error message as @ybm11 .
Was anyone able to solve this issue?

**Comment by halfak** [comment]
Regretfully, I don't have any concrete suggestions.  Do you get the above error when you run `arch -x86_64 /usr/local/bin/brew install enchant` or when you're trying to `pip install enchant`?

**Comment by Simonmaignan** [comment]
Hi everyone

The `-x86_64` workaround proposed by @undo76 didn't work on my computer because I ended up with the same `incompatible architecture` error mentioned by @ybm11 .
I focused on the missing enchant library original error.

After many hours of debugging, I finally understood why the `enchant C lib` was not found in my M1 MacOS.
It was a good MacOS exercise for me who is newbie with Mac.
It came all down to which version of `python` was called.

## Configuration
- MacBook M1 Pro
- MacOS Monterey 12.1
- Multiple version of python 3.9 or 3.10.

## Issue description
Here is what I understood of this issue.

Homebrew links the installed enchant library `libenchant-2.dylib` under
- `/usr/local/lib/` for the `-x86_64` version using `arch -x86_64 /usr/local/bin/brew install enchant`
- `/opt/homebrew/lib/` for the apple silicon version using `brew install enchant`
[Homebrew FAQ](https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location) about this topic.

Apparently, python can find libraries under `/opt/homebrew/lib/`, using [ctypes.util.find_library()](https://github.com/pyenchant/pyenchant/blob/main/enchant/_enchant.py#L114), only if it has been installed by homebrew with `brew install python` or if you tell it explicitly to.
All the other python versions (conda or system) seem to only look for the libraries under `/usr/local/lib/`.
I found information about this limitation under [this issue](https://githubmemory.com/repo/Kozea/WeasyPrint/issues/1451) (last comments) that point also to [this issue](https://github.com/Kozea/WeasyPrint/issues/1448#issuecomment-925559421).

## Solutions
### PYENCHANT_LIBRARY_PATH
One solution is to set the environment variable `PYENCHANT_LIBRARY_PATH=/opt/homebrew/lib/libenchant-2.2.dylib`. It activates the library search from [from_env_var()](https://github.com/pyenchant/pyenchant/blob/main/enchant/_enchant.py#L78).
Not really a generic and long term solution from my point of view.

### DYLD_LIBRARY_PATH
Reading around the web for the same type of error, I found that setting `DYLD_LIBRARY_PATH=/opt/homebrew/lib/` also worked for me.
Source in this [similar issue](https://github.com/shapely/shapely/issues/1080#issuecomment-778804819) with install of `shapely`.

### Python version
This would be the most generic and long term solution.
To make short: I had to make sure that the `python` and `pip` command used to install `pyenchant` and import `enchant` were the one installed with `brew install python`.
In my case the brew python version is installed under `/opt/homebrew/Cellar/python@3.9/3.9.9` and linked under `/opt/homebrew/bin` and no `python` symlink was set to point toward the brew `python3` binary.

Furthermore, I first used `conda miniforge` to manage my python environment and had a special environment set up for my `enchant` environment with its own python3.10 package installed. The `python` and `pip` commands pointed to the conda python version and not the brew ones. As explained above, the python installed by conda could by default only find the libraries under `/usr/local/lib/` and not under `/opt/homebrew/bin`.
After getting rid of miniforge (I'll find a way later to use it again) and uninstalling and reinstalling homebrew and brew python, I could set the proper `python` and `pip` symlink pointing to the `brew python3` binaries and it solved the `enchant C lib` not found issue.

@ybm11 and @undo76 , could you try to reproduce my 2 last solutions on your computers?

I hope I wasn't too boring to read and clear enough.

Regards and merry christmas

**Comment by Simonmaignan** [comment]
@ybm11 , after playing around with different versions of python, I understood and solved the `incompatible architecture` error you mentioned above.
It comes from the fact that we tried to open the `-x86_64` version of `enchant` with a native `arm64` version of python.

It's easy to mix the python versions running via Rosetta2 (`-x86_64`) and the native one (`arm64`). I advise to use `miniforge` (a fork of anaconda compatible with Mac-book ARM architecture) and create different environment for M1 native project and project that are only `-x86_64` compatible.
The simplest if you don't want to mix the different version is to use only anaconda which will run everything via Rosetta2, but you will lose some runtime performances.

Here are a few useful links to understand and set up the python environments for a M1.
- https://towardsdatascience.com/how-to-easily-set-up-python-on-any-m1-mac-5ea885b73fab
- https://www.anaconda.com/blog/apple-silicon-transition
- https://hendrik-erz.de/post/update-setting-up-python-numpy-and-pytorch-natively-on-apple-m1
- https://towardsdatascience.com/using-conda-on-an-m1-mac-b2df5608a141
- https://github.com/Haydnspass/miniforge#rosetta-on-mac-with-apple-silicon-hardware

**Comment by ybm11** [comment]
Hi @Simonmaignan 
Many thanks for the detailed solutions. 
Importing the packing on a Python version installed by `brew install python` works on my side as well.

**Comment by dmerejkowsky** [comment]
@Simonmaignan 
> After many hours of debugging, I finally understood why the enchant C lib was not found in my M1 MacOS [...]  It was a good MacOS exercise for me who is newbie with Mac.

Wow thanks for your help. Glad you learnt something, too.

>  To make short: I had to make sure that the python and pip command used to install pyenchant and import enchant were the one installed with brew install python.

Yeah, that's usually the root of many Python-related problems.

Do you think we should update PyEnchant's documentation ?

**Comment by Simonmaignan** [comment]
@dmerejkowsky , yes I guess a line or two about the python version mix up with Apple Silicon (M1) would be welcomed in the documentation.

My solution right now is to run everything in a  `conda` environment running the `-x86_64` python packages (because I have some dependencies which are not yet ported on M1). I also installed the `-x86_64` version of `enchant` using `homebrew`.

What bothers me is that I cannot set up a `conda` environment using native `arm64` environment and `import enchant` because the python version setup by the `conda` environment (`/opt/homebrew/Caskroom/miniforge/base/envs/<my-env-name>/bin/python`) only looks at binaries under `/usr/local/lib/` and not under `/opt/homebrew/lib/` (where the native `arm64` version of `enchant` is installed by `homebrew`).

Do you think this should be reported somewhere?

**Comment by dmerejkowsky** [comment]
I think the conda issue is a separate one. I've managed to reproduce the issue on Linux. See #279

**Comment by fredvd** [comment]
This issue has been closed and the suggested fix for installation problems on OS X with an M1 cpu seems to be to using a Python interpreter that runs Under Rosetta2 and requires you to have a full 'x86' install or Homebrew.  This very sub-optimal and also strange as a long term solution: many other Python packages with c library bindings run perfectly native on arm64/aarch64.  The enchant library itself is with 'M1' homebrew installed fine and runs natively as well from the command line. 

The root cause for the ctypes module not finding the '/opt/homebrew/lib/libenchant-2.dylib' on M1 macs is that the fallback  _enchant.py doesn't work on M1, which is a call to ctypes.util.find_library() for some variants of the library name. See https://github.com/pyenchant/pyenchant/blob/5e3eb94db0700c435b8812883d07199d05d99c54/enchant/_enchant.py#L100-L117

And no custom resolver has been added to _enchant.py for Windows where the .dll is found in a separate function. The find_library() function depends on the OS configuration for dynamic library linking.  When I create a new virtualenv and start my python 3.9 with:

`PYENCHANT_LIBRARY_PATH=/opt/homebrew/lib/libenchant-2.dylib PYENCHANT_VERBOSE_FIND=x python3`

importing pyenchant works fine. 

```
Python 3.9.11 (main, Apr 30 2022, 23:48:48)
[Clang 13.1.6 (clang-1316.0.21.2.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
pyenchant:: finding from prefix /opt/homebrew/lib
pyenchant:: no libenchant-2.dll found
pyenchant:: Prepending /opt/homebrew/lib/bin to %PATH%
pyenchant:: loading library /opt/homebrew/lib/libenchant-2.dylib
pyenchant:: setting prefix /opt/homebrew
```

To add to the confusion: the import problems happen with Python installations done using pyenv, but not when you are using a Python provided by Homebrew.  Most Python devs on Mac will sooner or later learn the hard way that depending on homebrew's Python package is cumbersome as homebrew will happily break your projects/virtualenvs when it upgrades Python and removes older versions because other packagesin the ecosystem use the newer Python release. 

The reason homebrew Pythons work is because Homebrew's Python formula explicitly patches the ctypes module to look for dynamic libraries in /opt/homebrew/lib if you call find_library:

https://github.com/Homebrew/homebrew-core/blob/2661c16ec39d8a10c097fda7205c6e903cb02d1e/Formula/python%403.9.rb#L185-L192

So, a longterm solutions for these problems is not using rosetta2, but fixing _enchant.py to look in /opt/homebrew/lib if the architecture is Darwin with aarch64, as is done for Windows

**Comment by dmerejkowsky** [comment]
> fixing _enchant.py to look in /opt/homebrew/lib if the architecture is Darwin with aarch64, as is done for Windows

@fredvd This looks reasonable but I don't know enough about homebrew, macOS and M1 to be sure it's a good idea.

Feel free to open a new issue - and send a patch :stuck_out_tongue:

**Comment by reagle** [comment]
I just ran into this and see this is closed and something is merged, but the merge is about documenting the build...?

**Comment by fredvd** [comment]
@reagle The merge you see is from the Plone documentation repo where we also have a section on how to contribute and how the documentation toolchain works.  We use Pyenchant in there. 

The workaround documented there is to run `export PYENCHANT_LIBRARY_PATH=/opt/homebrew/lib/libenchant-2.dylib` in the terminal session before you execute the python tool that uses Pyenchant on an M1 mac. 

https://github.com/plone/documentation/pull/1242/files#diff-ae34cc4176dbcc8623e692de94c8000e2caa8c84bf856211f0e0b96117b3faeb

**Comment by rghose** [comment]
@fredvd Thanks for the work-around, however since this issue is closed, can you please share the new issue that is supposed to include the long-term fix?
