### ISSUE TITLE
Ship libenchant with linux & mac wheels

### ISSUE THREAD

**Issue by tgross35** [pyenchant/pyenchant#291]
Out of curiosity, is there any reason that the Windows wheels ship with enchant, but the nix do not? I would vouch for adding support for at least one provider out of the box, to avoid the separate installation step.

**Comment by dmerejkowsky** [comment]
The main reason is that there's an easy way to install providers and dictionaries on macOs and nix system, because they are often shipped as distributions packages.

For instance `brew install hunspell-fr` or `apt install aspell-en` will work, and will also install the required  libenchant plugins (like enchant-hunspell or enchant-aspell).

There's no such thing as a "default" package manager on Windows, so we have to [work around that](https://pyenchant.github.io/pyenchant/install.html#installing-a-dictionary).

I think a better way would be to make installing providers and dict easy on windows, for instance using `scoop` or `chocolatey`.

By the way, if you're using `mingw`, you can *already* do that using `pacman`.

So Windows is the exception here, not the rule.
